apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aegis-lens-staging

resources:
  - namespace.yaml
  - ../configmaps
  - ../secrets
  - ../deployments
  - ../services
  - ../pvcs
  - ../ingress

images:
  - name: aegis-lens/candidate-ui
    newName: ghcr.io/lucieran-raven/aegis-lens/candidate-ui
    newTag: staging
  - name: aegis-lens/hr-dashboard
    newName: ghcr.io/lucieran-raven/aegis-lens/hr-dashboard
    newTag: staging
  - name: aegis-lens/agents
    newName: ghcr.io/lucieran-raven/aegis-lens/agents
    newTag: staging
  - name: aegis-lens/orchestrator
    newName: ghcr.io/lucieran-raven/aegis-lens/orchestrator
    newTag: staging

replicas:
  - name: candidate-ui
    count: 2
  - name: hr-dashboard
    count: 1
  - name: agents
    count: 2
  - name: orchestrator
    count: 1
