apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aegis-lens

resources:
  - namespace.yaml
  - configmaps/
  - secrets/
  - postgres/
  - timescaledb/
  - neo4j/
  - redis/
