-- Aegis Lens v2.0 - Session Migration
-- TimescaleDB hyper-table for session management
-- This table stores ephemeral session data with 5-minute TTL for validation

-- Enable TimescaleDB extension
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- Create schema versions table for migration tracking
CREATE TABLE IF NOT EXISTS schema_versions (
    version INTEGER PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    description TEXT NOT NULL
);

-- Insert initial schema version
INSERT INTO schema_versions (version, description)
    VALUES (1, 'Initial schema - sessions and events tables')
    ON CONFLICT (version) DO NOTHING;

-- Create sessions table
CREATE TABLE IF NOT EXISTS sessions (
    id BIGSERIAL PRIMARY KEY,
    session_id VARCHAR(64) UNIQUE NOT NULL,
    public_key_pem TEXT NOT NULL,
    client_nonce BYTEA NOT NULL,
    server_nonce BYTEA NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    client_ip VARCHAR(45),
    user_agent TEXT,
    status VARCHAR(20) DEFAULT 'active',

    -- Telemetry summary (for audit purposes only, no PII)
    last_verified_at TIMESTAMPTZ,
    verification_count INTEGER DEFAULT 0,
    total_score_avg NUMERIC(5,2),
    verdict VARCHAR(20)
);

-- Note: Hypertable conversion disabled for development
-- TimescaleDB requires partitioning column in primary key
-- Uncomment when schema is refactored for hypertable support
-- SELECT create_hypertable('sessions', 'created_at', if_not_exists => TRUE);

-- Create unique index on session_id
CREATE UNIQUE INDEX idx_sessions_session_id ON sessions(session_id);

-- Create indexes for fast lookups
CREATE INDEX idx_sessions_created_at ON sessions(created_at DESC);
CREATE INDEX idx_sessions_expires_at ON sessions(expires_at);
CREATE INDEX idx_sessions_status ON sessions(status) WHERE status = 'active';

-- Note: Compression and retention policies disabled for development
-- These require hypertable conversion
-- ALTER TABLE sessions SET (
--     timescaledb.compress,
--     timescaledb.compress_segmentby = 'session_id'
-- );
-- SELECT add_compression_policy('sessions', INTERVAL '1 hour');
-- SELECT add_retention_policy('sessions', INTERVAL '24 hours');

-- Create trigger for automatic cleanup of expired sessions
CREATE OR REPLACE FUNCTION cleanup_expired_sessions()
RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM sessions WHERE expires_at < NOW();
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Schedule cleanup to run every minute via pg_cron (if available)
-- SELECT cron.schedule('cleanup-expired-sessions', '* * * * *', 'SELECT cleanup_expired_sessions()');

-- Grant permissions (adjust based on your security model)
-- GRANT SELECT, INSERT, UPDATE ON sessions TO aegis_app;
-- GRANT USAGE, SELECT ON SEQUENCE sessions_id_seq TO aegis_app;

COMMENT ON TABLE sessions IS 'Aegis Lens session management hyper-table with 5-minute TTL and 24-hour retention';
COMMENT ON COLUMN sessions.session_id IS 'Unique session identifier (UUID)';
COMMENT ON COLUMN sessions.public_key_pem IS 'Client ECDSA P-256 public key in PEM format';
COMMENT ON COLUMN sessions.client_nonce IS '4-byte random nonce generated by client';
COMMENT ON COLUMN sessions.server_nonce IS '4-byte random nonce generated by server';
COMMENT ON COLUMN sessions.created_at IS 'Session creation timestamp';
COMMENT ON COLUMN sessions.expires_at IS 'Session expiration timestamp (created_at + 5 minutes)';
COMMENT ON COLUMN sessions.status IS 'Session status: active, expired, revoked';
COMMENT ON COLUMN sessions.verdict IS 'Final verdict: CLEAR, SUSPICIOUS, BLOCKED';
