apiVersion: v1
kind: Service
metadata:
  name: candidate-ui-service
  namespace: aegis-lens
  labels:
    app: candidate-ui
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: candidate-ui
