apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: aegis-lens
  labels:
    app: logs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
