apiVersion: v1
kind: Service
metadata:
  name: timescale-service
  namespace: aegis-lens
  labels:
    app: timescaledb
    component: database
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: timescaledb
  type: ClusterIP
