"""Initial TimescaleDB schema

Revision ID: fcfafc86db39
Revises: 
Create Date: 2026-07-22 16:57:25.058076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcfafc86db39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('position_applied', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resume_hash', sa.String(length=64), nullable=True),
    sa.Column('linkedin_hash', sa.String(length=64), nullable=True),
    sa.Column('github_hash', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_email_hash'), 'candidates', ['email_hash'], unique=True)
    op.create_table('system_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('metric_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_category', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_system_metrics_category_time', 'system_metrics', ['metric_category', 'metric_timestamp'], unique=False)
    op.create_index('idx_system_metrics_name_time', 'system_metrics', ['metric_name', 'metric_timestamp'], unique=False)
    op.create_index(op.f('ix_system_metrics_metric_category'), 'system_metrics', ['metric_category'], unique=False)
    op.create_index(op.f('ix_system_metrics_metric_timestamp'), 'system_metrics', ['metric_timestamp'], unique=False)
    op.create_table('intelligence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('intel_type', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_method', sa.String(length=50), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('has_discrepancy', sa.Boolean(), nullable=False),
    sa.Column('discrepancy_details', sa.Text(), nullable=True),
    sa.Column('evidence_urls', sa.JSON(), nullable=True),
    sa.Column('reference_contacts', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelligence_candidate_id'), 'intelligence', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_intelligence_source'), 'intelligence', ['source'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('interviewer_id', sa.String(length=36), nullable=True),
    sa.Column('interview_type', sa.String(length=50), nullable=False),
    sa.Column('browser_info', sa.Text(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('video_quality_score', sa.Float(), nullable=True),
    sa.Column('audio_quality_score', sa.Float(), nullable=True),
    sa.Column('network_quality_score', sa.Float(), nullable=True),
    sa.Column('final_verdict', sa.String(length=50), nullable=True),
    sa.Column('final_trust_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_candidate_id'), 'sessions', ['candidate_id'], unique=False)
    op.create_table('agent_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('metric_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_metrics_agent_time', 'agent_metrics', ['agent_name', 'metric_timestamp'], unique=False)
    op.create_index('idx_agent_metrics_session_time', 'agent_metrics', ['session_id', 'metric_timestamp'], unique=False)
    op.create_index(op.f('ix_agent_metrics_agent_name'), 'agent_metrics', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_metrics_metric_timestamp'), 'agent_metrics', ['metric_timestamp'], unique=False)
    op.create_index(op.f('ix_agent_metrics_session_id'), 'agent_metrics', ['session_id'], unique=False)
    op.create_table('agent_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('raw_data_id', sa.String(length=36), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_results_agent_name'), 'agent_results', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_results_session_id'), 'agent_results', ['session_id'], unique=False)
    op.create_table('physics_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('metric_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_physics_metrics_agent_time', 'physics_metrics', ['agent_name', 'metric_timestamp'], unique=False)
    op.create_index('idx_physics_metrics_session_time', 'physics_metrics', ['session_id', 'metric_timestamp'], unique=False)
    op.create_index(op.f('ix_physics_metrics_agent_name'), 'physics_metrics', ['agent_name'], unique=False)
    op.create_index(op.f('ix_physics_metrics_metric_timestamp'), 'physics_metrics', ['metric_timestamp'], unique=False)
    op.create_index(op.f('ix_physics_metrics_session_id'), 'physics_metrics', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_physics_metrics_session_id'), table_name='physics_metrics')
    op.drop_index(op.f('ix_physics_metrics_metric_timestamp'), table_name='physics_metrics')
    op.drop_index(op.f('ix_physics_metrics_agent_name'), table_name='physics_metrics')
    op.drop_index('idx_physics_metrics_session_time', table_name='physics_metrics')
    op.drop_index('idx_physics_metrics_agent_time', table_name='physics_metrics')
    op.drop_table('physics_metrics')
    op.drop_index(op.f('ix_agent_results_session_id'), table_name='agent_results')
    op.drop_index(op.f('ix_agent_results_agent_name'), table_name='agent_results')
    op.drop_table('agent_results')
    op.drop_index(op.f('ix_agent_metrics_session_id'), table_name='agent_metrics')
    op.drop_index(op.f('ix_agent_metrics_metric_timestamp'), table_name='agent_metrics')
    op.drop_index(op.f('ix_agent_metrics_agent_name'), table_name='agent_metrics')
    op.drop_index('idx_agent_metrics_session_time', table_name='agent_metrics')
    op.drop_index('idx_agent_metrics_agent_time', table_name='agent_metrics')
    op.drop_table('agent_metrics')
    op.drop_index(op.f('ix_sessions_candidate_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_intelligence_source'), table_name='intelligence')
    op.drop_index(op.f('ix_intelligence_candidate_id'), table_name='intelligence')
    op.drop_table('intelligence')
    op.drop_index(op.f('ix_system_metrics_metric_timestamp'), table_name='system_metrics')
    op.drop_index(op.f('ix_system_metrics_metric_category'), table_name='system_metrics')
    op.drop_index('idx_system_metrics_name_time', table_name='system_metrics')
    op.drop_index('idx_system_metrics_category_time', table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_index(op.f('ix_candidates_email_hash'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
